export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILE_SHORTLIST = 'GET_PROFILE_SHORTLIST';
export const GET_PROFILES = 'GET_PROFILES';
export const PROFILE_ERROR = 'PROFILE_ERROR';

export const GET_ALL_ACCOUNTS = 'GET_ALL_ACCOUNTS';
export const GET_ACCOUNT = 'GET_ACCOUNT';
export const ACCOUNTS_LOADING = 'ACCOUNTS_LOADING';
export const ACCOUNTS_ERROR = 'ACCOUNTS_ERROR';
export const CLEAR_ALL_ACCOUNTS = 'CLEAR_ALL_ACCOUNTS';